#!/usr/bin/env bash
set -euo pipefail
CONDA_ENV="${CONDA_ENV:-torchhuy}"; PROTOCOL_ROOT="${PROTOCOL_ROOT:-runs/phase4/progress1_v7_full_seed0_ready}"
EPOCHS="${EPOCHS:-20}"; BATCH_SIZE="${BATCH_SIZE:-1}"; GRAD_ACCUM="${GRAD_ACCUM:-6}"; NUM_WORKERS="${NUM_WORKERS:-4}"
PRECISION="${PRECISION:-bf16}"; SEED="${SEED:-0}"; CUDA_DEVICE="${CUDA_DEVICE:-0}"; TEST_BATCH_SIZE="${TEST_BATCH_SIZE:-1}"
VALIDATION_EPOCHS="${VALIDATION_EPOCHS:-8 9 10 11 12 13 14 15 16 17 18 19 20}"; STAGE="${STAGE:-all}"
FORCE_RETRAIN="${FORCE_RETRAIN:-0}"; DRY_RUN="${DRY_RUN:-0}"; ALLOW_EXACT_TEST_RERUN="${ALLOW_EXACT_TEST_RERUN:-0}"
SMOKE_MAX_BATCHES="${SMOKE_MAX_BATCHES:-0}"
DRIFT_DIAGNOSTICS="${DRIFT_DIAGNOSTICS:-0}"
H6_STRUCTURAL_GATE_MODE="${H6_STRUCTURAL_GATE_MODE:-monitor}"
export CONDA_ENV PROTOCOL_ROOT EPOCHS BATCH_SIZE GRAD_ACCUM NUM_WORKERS PRECISION SEED CUDA_DEVICE TEST_BATCH_SIZE VALIDATION_EPOCHS STAGE FORCE_RETRAIN DRY_RUN ALLOW_EXACT_TEST_RERUN SMOKE_MAX_BATCHES DRIFT_DIAGNOSTICS H6_STRUCTURAL_GATE_MODE
conda run --no-capture-output -n "${CONDA_ENV}" python tools/phase4_v7_full_protocol.py
