#!/usr/bin/env bash
set -euo pipefail

SAVE_PATH="${SAVE_PATH:-runs/phase4/progress1_v4_diagnostic_seed0}"
EPOCHS="${EPOCHS:-3}"
BATCH_SIZE="${BATCH_SIZE:-1}"
GRAD_ACCUM="${GRAD_ACCUM:-6}"
NUM_WORKERS="${NUM_WORKERS:-6}"
PRECISION="${PRECISION:-bf16}"
SEED="${SEED:-0}"
CUDA_DEVICE="${CUDA_DEVICE:-0}"
H6_DENSE_ROUTING_EPOCHS="${H6_DENSE_ROUTING_EPOCHS:-8}"
H6_SPARSE_TRANSITION_EPOCHS="${H6_SPARSE_TRANSITION_EPOCHS:-4}"

echo "[PHASE4-P1-V4-DIAG] train_only=true medical_val=false medical_test=false save_path=${SAVE_PATH}"

SAVE_PATH="${SAVE_PATH}" \
EPOCHS="${EPOCHS}" \
BATCH_SIZE="${BATCH_SIZE}" \
GRAD_ACCUM="${GRAD_ACCUM}" \
NUM_WORKERS="${NUM_WORKERS}" \
PRECISION="${PRECISION}" \
SEED="${SEED}" \
CUDA_DEVICE="${CUDA_DEVICE}" \
H6_DENSE_ROUTING_EPOCHS="${H6_DENSE_ROUTING_EPOCHS}" \
H6_SPARSE_TRANSITION_EPOCHS="${H6_SPARSE_TRANSITION_EPOCHS}" \
H6_SLOT_INIT_ENABLED=1 \
LAMBDA_H6_CONCEPT_KEY_DIVERSITY=0.0001 \
H6_FACTOR_GRAD_DIAGNOSTICS=1 \
bash scripts/phase4/run_progress1_v4_train.sh
