#!/usr/bin/env bash
# Generated by the canonical Medical-resume audit.  It is intentionally not
# executed by the audit; run it explicitly with:
#   bash scripts/canonical/RESUME_CANONICAL_MEDICAL.sh
set -euo pipefail

REPO_ROOT="/home/ai4/caohuy/ACD-CLIP-sabra-canonical-v1"
EXPECTED_SCIENTIFIC_SHA="4aa9b465ddeb072e9218b74982306d6324c62375"

cd /home/ai4/caohuy/ACD-CLIP-sabra-canonical-v1
export MVTEC_ROOT=/home/ai4/caohuy/data/mvtec_ad
export MEDICAL_ROOT=/home/ai4/caohuy/data
export VISA_ROOT=/home/ai4/caohuy/data/VisA_20220922
export RUN_ROOT=/home/ai4/caohuy/acdclip_runs/canonical_sabra_v1_seed0
export PYTHON="${PYTHON:-/home/ai4/ENTER/envs/torchhuy/bin/python}"

selection_json="$RUN_ROOT/phase2b_selection/phase2b_selection.json"
freeze_json="$RUN_ROOT/sabra_lambda/SABRA_FREEZE.json"
datasets=(Brain Liver Retina Colon_clinicDB Colon_colonDB Colon_Kvasir)

[[ -x "$PYTHON" ]] || { printf 'ERROR: Python executable is unavailable: %s\n' "$PYTHON" >&2; exit 1; }

# This is the canonical Medical freeze guard, performed before any Medical
# inference or output mutation.  It reads only the frozen artifacts and the
# selected checkpoint.
"$PYTHON" - "$selection_json" "$freeze_json" "$EXPECTED_SCIENTIFIC_SHA" <<'PY'
import hashlib
import sys
from pathlib import Path

from tools.sabra.artifacts import load_json, validate_sabra_freeze

selection = load_json(sys.argv[1])
freeze = load_json(sys.argv[2])
expected_scientific_sha = sys.argv[3]

if selection.get("status") != "FROZEN":
    raise SystemExit("Phase2B selection must be FROZEN before Medical evaluation")
checkpoint = Path(str(selection.get("selected_checkpoint", ""))).expanduser()
expected_checkpoint_sha = str(selection.get("selected_checkpoint_sha256", ""))
if not checkpoint.is_file() or not expected_checkpoint_sha:
    raise SystemExit("Phase2B selection lacks a valid selected checkpoint")
digest = hashlib.sha256()
with checkpoint.open("rb") as handle:
    for block in iter(lambda: handle.read(1024 * 1024), b""):
        digest.update(block)
actual_checkpoint_sha = digest.hexdigest()
if actual_checkpoint_sha != expected_checkpoint_sha:
    raise SystemExit("Phase2B selected checkpoint SHA256 mismatch")
validate_sabra_freeze(freeze, checkpoint_sha256=actual_checkpoint_sha)
if freeze.get("provenance", {}).get("git_sha") != expected_scientific_sha:
    raise SystemExit("SABRA freeze provenance SHA differs from the canonical scientific code SHA")
if str(freeze.get("relational", {}).get("backend", "")).lower() != "fast":
    raise SystemExit("Medical evaluation requires the frozen fast relational backend")
if freeze.get("medical_seen") is not False:
    raise SystemExit("SABRA freeze is not Medical-clean")
print(f"MEDICAL_GUARD=PASS checkpoint_sha256={actual_checkpoint_sha} backend=fast medical_seen=false")
PY

# Refuse concurrent final-Medical execution before touching logs or outputs.
active_medical=""
if command -v pgrep >/dev/null 2>&1; then
  active_medical="$(pgrep -af '[m]edical_compare_external.py|[5]0_eval_medical.sh|run_pipeline.sh[[:space:]]+medical|test.py.*--dataset[[:space:]]+(Brain|Liver|Retina|Colon_)' || true)"
fi
if [[ -n "$active_medical" ]]; then
  printf 'ERROR: a canonical Medical process is already active:\n%s\n' "$active_medical" >&2
  exit 1
fi

# Preserve both historical Brain attempts.  Move the latest OOM log only when
# the deterministic destination is still free; never overwrite either backup.
brain_log="$RUN_ROOT/logs/medical_Brain.log"
brain_oom_backup="$RUN_ROOT/logs/medical_Brain.oom_kill_backup.log"
if [[ -e "$brain_log" && ! -e "$brain_oom_backup" ]]; then
  mv -- "$brain_log" "$brain_oom_backup"
elif [[ -e "$brain_log" && -e "$brain_oom_backup" ]]; then
  printf 'BRAIN_LOG_PRESERVED source=%s backup=%s\n' "$brain_log" "$brain_oom_backup"
fi

# Audit all six outputs.  Completed datasets are validated and preserved;
# partial/not-started datasets are left for the cache-aware Stage 5 loop.
need_medical=0
for dataset in "${datasets[@]}"; do
  output_dir="$RUN_ROOT/medical/$dataset"
  metrics_path="$output_dir/metrics.json"
  csv_path="$output_dir/per_class_metrics.csv"
  if [[ -f "$metrics_path" && -f "$csv_path" ]]; then
    "$PYTHON" - "$metrics_path" "$csv_path" "$dataset" "$selection_json" "$freeze_json" <<'PY'
import csv
import hashlib
import json
import sys
from pathlib import Path

metrics_path = Path(sys.argv[1])
csv_path = Path(sys.argv[2])
dataset = sys.argv[3]
selection = json.loads(Path(sys.argv[4]).read_text(encoding="utf-8"))
freeze_path = Path(sys.argv[5])
expected_checkpoint_sha = selection.get("selected_checkpoint_sha256")
expected_freeze_sha = hashlib.sha256(freeze_path.read_bytes()).hexdigest()
payload = json.loads(metrics_path.read_text(encoding="utf-8"))
if payload.get("dataset") != dataset or payload.get("role") != "FINAL_ZERO_SHOT":
    raise SystemExit(f"Medical result identity mismatch for {dataset}")
if payload.get("phase2b_checkpoint_sha256") != expected_checkpoint_sha:
    raise SystemExit(f"Medical result checkpoint mismatch for {dataset}")
if payload.get("sabra_freeze_sha256") != expected_freeze_sha:
    raise SystemExit(f"Medical result freeze mismatch for {dataset}")
for key in ("phase2b", "phase2b_macro", "phase2b_metrics", "sabra", "sabra_macro", "sabra_metrics", "delta", "runtime"):
    if not isinstance(payload.get(key), dict):
        raise SystemExit(f"Medical result lacks {key} for {dataset}")
with csv_path.open(newline="", encoding="utf-8") as handle:
    if not list(csv.DictReader(handle)):
        raise SystemExit(f"Medical per-class CSV is empty for {dataset}")
PY
    printf 'MEDICAL_RESUME_AUDIT dataset=%s status=COMPLETE\n' "$dataset"
  else
    need_medical=1
    if [[ -e "$metrics_path" || -e "$csv_path" ]] || { [[ -d "$output_dir" ]] && [[ -n "$(find "$output_dir" -mindepth 1 -maxdepth 1 -print -quit)" ]]; }; then
      printf 'MEDICAL_RESUME_AUDIT dataset=%s status=PARTIAL\n' "$dataset"
    else
      printf 'MEDICAL_RESUME_AUDIT dataset=%s status=NOT_STARTED\n' "$dataset"
    fi
  fi
done

# This invokes only Stage 5.  It skips validated completed outputs, reuses every
# valid completed inference cache for metrics-only work, and never runs earlier stages.
if [[ "$need_medical" == "1" ]]; then
  ./scripts/canonical/run_pipeline.sh medical
fi

# Export is permitted only after the complete six-dataset final contract exists.
"$PYTHON" - "$RUN_ROOT" <<'PY'
import json
import sys
from pathlib import Path

run_root = Path(sys.argv[1])
datasets = ["Brain", "Liver", "Retina", "Colon_clinicDB", "Colon_colonDB", "Colon_Kvasir"]
for dataset in datasets:
    output_dir = run_root / "medical" / dataset
    metrics_path = output_dir / "metrics.json"
    csv_path = output_dir / "per_class_metrics.csv"
    if not metrics_path.is_file() or not csv_path.is_file():
        raise SystemExit(f"Medical result incomplete for {dataset}; refusing export")
    try:
        metrics = json.loads(metrics_path.read_text(encoding="utf-8"))
    except Exception as exc:
        raise SystemExit(f"Medical metrics JSON is invalid for {dataset}: {exc}") from exc
    if metrics.get("dataset") != dataset:
        raise SystemExit(f"Medical metrics dataset mismatch for {dataset}")
    if not isinstance(metrics.get("phase2b"), dict) or not isinstance(metrics.get("sabra"), dict):
        raise SystemExit(f"Medical compare sections are missing for {dataset}")
print("MEDICAL_COMPLETE_CONTRACT=PASS")
PY

./scripts/canonical/run_pipeline.sh export
