#!/usr/bin/env bash
set -euo pipefail

SAVE_PATH="${SAVE_PATH:-runs/phase3b/phase3b_stagecons_alpha02_kreg2e3_lstage2e3_js_warm5_bf16_train15}"
LAMBDA_STAGE="${LAMBDA_STAGE:-0.002}"
STAGE_CONSISTENCY_LOSS="${STAGE_CONSISTENCY_LOSS:-js}"
STAGE_CONSISTENCY_MARGIN="${STAGE_CONSISTENCY_MARGIN:-0.0}"
STAGE_CONSISTENCY_WARMUP_EPOCHS="${STAGE_CONSISTENCY_WARMUP_EPOCHS:-5}"
AMP_DTYPE="${AMP_DTYPE:-bf16}"

SAVE_PATH="${SAVE_PATH}" \
LAMBDA_STAGE="${LAMBDA_STAGE}" \
STAGE_CONSISTENCY_LOSS="${STAGE_CONSISTENCY_LOSS}" \
STAGE_CONSISTENCY_MARGIN="${STAGE_CONSISTENCY_MARGIN}" \
STAGE_CONSISTENCY_WARMUP_EPOCHS="${STAGE_CONSISTENCY_WARMUP_EPOCHS}" \
AMP_DTYPE="${AMP_DTYPE}" \
bash run_phase3b_stagecons_alpha02_kreg2e3_lstage5e4_m002_train15.sh
