"""Opt-in contracts for the clean H2 research trajectory."""

from .contract import (
    ANCHOR_FORMULA,
    ANCHOR_FAMILY_BUDGET_DEFAULT,
    ANCHOR_LAMBDA_ACTIVE,
    ANCHOR_LAMBDA_OLD,
    ANCHOR_R_MED,
    ANCHOR_TARGET_EFFECTIVE_RATIO,
    PRIMARY_HORIZON,
    PROTOCOL_VERSION,
    SafeImageAdapterAnchor,
    SECONDARY_HORIZON,
    TRAINING_HORIZON,
)
from .cir_v2 import (
    CIR_EPS,
    FROZEN_CIR_COMMIT,
    MAD_CONSTANT,
    V2_TRANSPORT_DIRECTION,
    cir_logits_from_native_weights,
    gather_peer_values,
    midpoint_median,
    peer_delta_from_native_margins,
    robust_peer_delta,
    score_optimized,
    score_reference,
    select_gt_free_peers,
    transport_pair,
    transport_weights,
)

__all__ = [
    "ANCHOR_FORMULA",
    "ANCHOR_FAMILY_BUDGET_DEFAULT",
    "ANCHOR_LAMBDA_ACTIVE",
    "ANCHOR_LAMBDA_OLD",
    "ANCHOR_R_MED",
    "ANCHOR_TARGET_EFFECTIVE_RATIO",
    "PRIMARY_HORIZON",
    "PROTOCOL_VERSION",
    "SafeImageAdapterAnchor",
    "SECONDARY_HORIZON",
    "TRAINING_HORIZON",
    "CIR_EPS",
    "FROZEN_CIR_COMMIT",
    "MAD_CONSTANT",
    "V2_TRANSPORT_DIRECTION",
    "cir_logits_from_native_weights",
    "gather_peer_values",
    "midpoint_median",
    "peer_delta_from_native_margins",
    "robust_peer_delta",
    "score_optimized",
    "score_reference",
    "select_gt_free_peers",
    "transport_pair",
    "transport_weights",
]
