#!/usr/bin/env python3
"""Protocol-matched comparison for Phase2B, Phase4 P1-v1, and Phase4 P1-v2.

This tool only compares already-generated summary CSVs.  It does not infer
missing results, rescore epochs, or mix validation-selected and test-selected
protocols.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import pandas as pd


METHODS = ("phase2b", "p1_v1", "p1_v2")
DATASET_COLUMNS = ("dataset", "epoch")
METRIC_COLUMNS = (
    "image_AUROC",
    "image_AP",
    "pixel_AUROC",
    "pixel_AP",
    "image_score",
    "pixel_score",
    "combined_score",
)


def _summary_csv(run_dir: Path, split: str, by: str) -> Path:
    return run_dir / f"medical_{split}_results_by_{by}.csv"


def read_method(name: str, run_dir_text: str | None, split: str, require: bool) -> tuple[pd.DataFrame | None, dict]:
    status = {
        "method": name,
        "run_dir": run_dir_text,
        "loaded": False,
        "missing": [],
    }
    if run_dir_text is None:
        status["missing"].append("not supplied")
        if require:
            raise FileNotFoundError(f"{name}: run directory was not supplied")
        return None, status

    run_dir = Path(run_dir_text)
    by_dataset = _summary_csv(run_dir, split, "dataset")
    if not by_dataset.is_file():
        status["missing"].append(str(by_dataset))
        if require:
            raise FileNotFoundError(f"{name}: missing {by_dataset}")
        return None, status

    frame = pd.read_csv(by_dataset)
    missing_columns = [column for column in (*DATASET_COLUMNS, *METRIC_COLUMNS) if column not in frame.columns]
    if missing_columns:
        raise ValueError(f"{name}: {by_dataset} is missing columns: {missing_columns}")
    frame = frame.loc[:, [*DATASET_COLUMNS, *METRIC_COLUMNS]].copy()
    frame.insert(0, "method", name)
    status["loaded"] = True
    status["rows"] = int(len(frame))
    status["datasets"] = sorted(frame["dataset"].astype(str).unique().tolist())
    status["epochs"] = sorted(int(epoch) for epoch in frame["epoch"].unique().tolist())
    return frame, status


def main() -> None:
    parser = argparse.ArgumentParser(description="Compare protocol-matched six-medical summary CSVs")
    parser.add_argument("--phase2b", default=None, help="Directory containing medical_<split>_results_by_dataset.csv")
    parser.add_argument("--p1-v1", dest="p1_v1", default=None, help="Directory containing medical_<split>_results_by_dataset.csv")
    parser.add_argument("--p1-v2", dest="p1_v2", default=None, help="Directory containing medical_<split>_results_by_dataset.csv")
    parser.add_argument("--split", choices=["val", "test"], default="test")
    parser.add_argument("--output-dir", required=True)
    parser.add_argument("--allow-missing", action="store_true", help="Write a partial comparison instead of failing on missing methods")
    args = parser.parse_args()

    frames = []
    statuses = []
    for method in METHODS:
        frame, status = read_method(
            method,
            getattr(args, method),
            args.split,
            require=not args.allow_missing,
        )
        statuses.append(status)
        if frame is not None:
            frames.append(frame)
    if not frames:
        raise FileNotFoundError("no method summary CSVs were loaded")

    combined = pd.concat(frames, ignore_index=True)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)
    combined.to_csv(output_dir / f"comparison_{args.split}_by_dataset.csv", index=False)

    macro = combined.groupby(["method", "epoch"], as_index=False)[list(METRIC_COLUMNS)].mean()
    macro.to_csv(output_dir / f"comparison_{args.split}_by_epoch.csv", index=False)

    deltas = []
    if set(combined["method"]) >= {"phase2b", "p1_v2"}:
        left = combined[combined["method"] == "phase2b"]
        right = combined[combined["method"] == "p1_v2"]
        merged = right.merge(left, on=["dataset"], suffixes=("_p1_v2", "_phase2b"))
        for _, row in merged.iterrows():
            deltas.append({
                "dataset": row["dataset"],
                "p1_v2_epoch": int(row["epoch_p1_v2"]),
                "phase2b_epoch": int(row["epoch_phase2b"]),
                "combined_score_delta_p1_v2_minus_phase2b": float(row["combined_score_p1_v2"] - row["combined_score_phase2b"]),
                "image_score_delta_p1_v2_minus_phase2b": float(row["image_score_p1_v2"] - row["image_score_phase2b"]),
                "pixel_score_delta_p1_v2_minus_phase2b": float(row["pixel_score_p1_v2"] - row["pixel_score_phase2b"]),
            })
        pd.DataFrame(deltas).to_csv(output_dir / f"comparison_{args.split}_p1_v2_minus_phase2b.csv", index=False)

    summary = {
        "split": args.split,
        "protocol_note": "All inputs must be generated by the same split protocol; this tool only compares supplied summary CSVs.",
        "methods": statuses,
        "macro": macro.to_dict(orient="records"),
        "p1_v2_minus_phase2b": deltas,
    }
    (output_dir / f"comparison_{args.split}_summary.json").write_text(
        json.dumps(summary, indent=2, sort_keys=True) + "\n"
    )
    print(json.dumps(summary, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
